export const ADD_ARTICLE = 'ADD_ARTICLE';
export const SET_CATEGORY_FILTER = 'SET_CATEGORY_FILTER';
export const DELETE_ARTICLE = 'DELETE_ARTICLE';
export const FETCH_ARTICLES_START = 'FETCH_ARTICLES_START';
export const FETCH_ARTICLES_ERROR = 'FETCH_ARTICLES_ERROR';
export const RECEIVE_ARTICLES = 'RECEIVE_ARTICLES';
